[package]
name = "yzesd-zsittle"
version = "0.1.0"
authors = ["Erik Zscheile <zseri.devel@ytrizja.de>"]
edition = "2018"
publish = false

[dependencies]
base64 = "0.12"
clap = "2.33"
smol = "0.1"
yz-encsess = { path = "../lib" }
futures-channel = "0.3.5"
ctrlc = "3.1.4"
tracing-subscriber = "0.2.5"
memchr = "2.3.3"

[dependencies.futures-util]
version = "0.3"
features = ["unstable", "bilock"]

[dependencies.smol-potat]
version = "0.3"
features = ["auto"]
