[package]
name = "packet-stream"
version = "0.1.0"
authors = ["Erik Zscheile <zseri.devel@ytrizja.de>"]
edition = "2018"

[dependencies]
bytes = "0.5"
futures-core = "0.3"
futures-io = "0.3"
futures-sink = "0.3"
pin-project-lite = "0.1"
pin-utils = "0.1"
tracing = "0.1"
